
# By default, this function reads template files in /etc/nginx/templates/*.template and outputs the result of executing envsubst to /etc/nginx/conf.d.
  # see here for details https://hub.docker.com/_/nginx

services:
  nginx:
    image: "nginx"
    volumes:
      - "./:/html"
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
      - NGINX_SAFE_PORT=8080
    networks:
      - ngrok

# for some reason the ngrok messages don't make it out to the log
  # go to localhost:4040 to see the running gateway and use that to get the url
  ngrok:
    image: "ngrok/ngrok"
    ports: 
      - "4040:4040"
    command:
      - "start"
      - "--all"
      - "--config"
      - "/ngrok.yml"
    volumes:
      - ./ngrok.yml:/ngrok.yml
    networks:
      - ngrok
    depends_on:
      - nginx

networks:
  ngrok:
    driver: "bridge"
